# Generated by Django 4.1.7 on 2023-06-16 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD1', '0002_cliente_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datosentrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de venta')),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancia por dia')),
            ],
        ),
        migrations.CreateModel(
            name='Datosventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de venta')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
                ('cantidad_venta', models.IntegerField(verbose_name='Cantidad de Productos Vendidos')),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancia por dia')),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD1.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
