# Generated by Django 4.1.7 on 2023-06-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD1', '0003_datosentrenamiento_datosventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datosventasentrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de venta')),
                ('mes_entrenamiento', models.CharField(choices=[('enero', 'Enero'), ('febrero', 'Febrero'), ('marzo', 'Marzo'), ('abril', 'Abril'), ('mayo', 'Mayo'), ('junio', 'Junio'), ('julio', 'Julio'), ('agosto', 'Agosto'), ('septiembre', 'Septiembre'), ('octubre', 'Octubre'), ('noviembre', 'Noviembre'), ('diciembre', 'Diciembre')], max_length=20, verbose_name='Mes de entrenamiento')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
                ('cantidad_venta', models.IntegerField(verbose_name='Cantidad de Productos Vendidos')),
                ('ganancia', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Ganancia por día')),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD1.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de venta')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
                ('cantidad_venta', models.IntegerField(verbose_name='Cantidad de Productos Vendidos')),
                ('ganancia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ganancia por día')),
                ('cod_datosentrenamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD1.datosentrenamiento', verbose_name='Datos de entrenamiento predeterminados')),
                ('cod_datosventasentrenamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD1.datosventasentrenamiento', verbose_name='Datos de entrenamiento del Usuario')),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD1.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Datosventas',
        ),
    ]
