# Generated by Django 4.1.7 on 2023-06-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD1', '0005_datospredeterminados_datosventausuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospredeterminados',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='datospredeterminados',
            name='ganancia',
        ),
        migrations.AddField(
            model_name='datospredeterminados',
            name='datos',
            field=models.JSONField(default=dict, verbose_name='Datos de venta'),
        ),
        migrations.AlterField(
            model_name='datosventausuario',
            name='datos',
            field=models.JSONField(default=dict, verbose_name='Datos de venta'),
        ),
        migrations.AlterField(
            model_name='prediccionventa',
            name='datos',
            field=models.JSONField(default=dict, verbose_name='Datos de la predicción'),
        ),
    ]
