# Generated by Django 4.1.7 on 2023-06-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD1', '0007_alter_datosventausuario_cod_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionventa',
            name='modelo_usado',
            field=models.CharField(choices=[('sarima', 'Sarima'), ('ols', 'Ordinary Least Squares (OLS)'), ('lstm', 'Red neuronal (LSTM)')], default='Sarima', max_length=50, verbose_name='Modelo usado'),
        ),
    ]
