# Generated by Django 4.1.7 on 2023-06-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD1', '0008_prediccionventa_modelo_usado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccionventa',
            name='cod_entrenamiento_predeterminado',
        ),
        migrations.AlterField(
            model_name='prediccionventa',
            name='modelo_usado',
            field=models.CharField(choices=[('sarima', 'Sarima'), ('ols', 'Ordinary Least Squares (OLS)')], default='Sarima', max_length=50, verbose_name='Modelo usado'),
        ),
        migrations.DeleteModel(
            name='Datospredeterminados',
        ),
    ]
