# Generated by Django 4.1.7 on 2023-07-01 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD1', '0009_remove_prediccionventa_cod_entrenamiento_predeterminado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD1.producto', verbose_name='Producto')),
            ],
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Vendedor',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD1.vendedor', verbose_name='Vendedor'),
        ),
    ]
