# Generated by Django 4.1.7 on 2023-07-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD1', '0010_producto_venta_rename_cliente_vendedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='precio',
        ),
        migrations.AddField(
            model_name='venta',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10, verbose_name='Monto Vendido'),
        ),
    ]
