# Generated by Django 4.1.7 on 2023-07-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD1', '0011_remove_venta_precio_venta_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Vendido'),
        ),
    ]
