# Generated by Django 4.1.7 on 2023-07-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD1', '0012_alter_venta_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad Vendida'),
        ),
    ]
